#include <mpi.h>    // Required for MPI functions
#include <stdio.h>  // Required for standard input/output (printf, scanf)
#include <stdlib.h> // Required for general utilities (rand, srand)
#include <time.h>   // Required for time() to seed the random number generator

int main(int argc, char **argv)
{
    int rank;      // Rank of the current process (0 to num_procs-1)
    int num_procs; // Total number of processes in the communicator

    // 1. Inicialización MPI
    // Initialize the MPI environment. This must be called before any other MPI function.
    MPI_Init(&argc, &argv);

    // Get the rank of the current process within MPI_COMM_WORLD
    // MPI_COMM_WORLD is the default communicator that includes all processes.
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    // Get the total number of processes in MPI_COMM_WORLD
    MPI_Comm_size(MPI_COMM_WORLD, &num_procs);

    int N; // N: Number of random values each process will generate

    // 2. Generación de datos y Broadcast de N
    // Only the root process (rank 0) asks the user for N.
    if (rank == 0)
    {
        printf("Proceso Raiz (Rank 0): Ingrese el tamaño N (cantidad de valores por proceso): ");
        // Read N from user input
        if (scanf("%d", &N) != 1 || N <= 0)
        {
            printf("Error: N debe ser un entero positivo. Terminando el programa.\n");
            // If input is invalid, terminate all processes gracefully.
            MPI_Abort(MPI_COMM_WORLD, 1);
        }
        printf("Proceso Raiz (Rank 0): N = %d. Distribuyendo N a todos los procesos.\n", N);
    }

    // Broadcast N from the root process (rank 0) to all other processes.
    // All processes (including root) call MPI_Bcast.
    // Arguments:
    //   - &N: Address of the variable to send/receive.
    //   - 1: Number of elements to send/receive.
    //   - MPI_INT: Data type of the elements.
    //   - 0: Rank of the root process (the sender).
    //   - MPI_COMM_WORLD: The communicator group.
    MPI_Bcast(&N, 1, MPI_INT, 0, MPI_COMM_WORLD);

    // After MPI_Bcast, all processes have the correct value of N.
    printf("Proceso %d: N recibido = %d.\n", rank, N);

    // 3. Generación local de valores y cálculo de suma parcial
    // Seed the random number generator using time and rank to ensure different sequences
    // for each process, even if they start at the same time.
    srand(time(NULL) + rank);

    double partial_sum = 0.0; // Variable to store the sum of locally generated values
    printf("Proceso %d: Generando %d valores aleatorios...\n", rank, N);

    // Generate N random double values and calculate their sum.
    for (int i = 0; i < N; ++i)
    {
        // Generate a random double between 0.0 and 100.0 (inclusive)
        double value = (double)rand() / RAND_MAX * 100.0;
        partial_sum += value;
        // Optional: Uncomment to see individual values generated by each process
        // printf("Proceso %d, Valor %d: %f\n", rank, i, value);
    }
    printf("Proceso %d: Suma parcial calculada = %f\n", rank, partial_sum);

    // 4. Reducción de la suma (MPI_Reduce)
    double total_sum; // Variable to store the sum of all partial sums (only valid on root)

    // Reduce all partial sums to the root process (rank 0).
    // The operation is MPI_SUM (addition).
    // Arguments:
    //   - &partial_sum: Send buffer (each process's partial sum).
    //   - &total_sum: Receive buffer (only significant on root, where the final sum is stored).
    //   - 1: Number of elements to reduce.
    //   - MPI_DOUBLE: Data type of the elements.
    //   - MPI_SUM: The reduction operation (summation).
    //   - 0: Rank of the root process (where the final result will reside).
    //   - MPI_COMM_WORLD: The communicator group.
    MPI_Reduce(&partial_sum, &total_sum, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);

    double average_total; // Variable to store the final average

    // 5. Distribución del promedio (MPI_Bcast)
    // Only the root process calculates the total average.
    if (rank == 0)
    {
        // Total number of values generated across all processes
        long long total_values = (long long)N * num_procs;
        average_total = total_sum / (double)total_values;
        printf("Proceso Raiz (Rank 0): Suma total de todos los valores = %f\n", total_sum);
        printf("Proceso Raiz (Rank 0): Promedio total calculado = %f\n", average_total);
    }

    // Broadcast the calculated total average from the root process (rank 0) to all processes.
    // This ensures all processes have the final average to print.
    MPI_Bcast(&average_total, 1, MPI_DOUBLE, 0, MPI_COMM_WORLD);

    // 6. Visualización del promedio
    // Each process prints the received total average along with its rank.
    printf("Proceso %d: Promedio total recibido = %f\n", rank, average_total);

    // 7. Finalización
    // Finalize the MPI environment. This must be called at the end of the MPI program.
    MPI_Finalize();

    return 0;
}
